# Generated by Django 6.0.4 on 2026-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
